### PR TITLE
Lexer cleanup

### PR DESCRIPTION
**Pull request by SimplyTheOther**
This PR improves code quality in the lexer. 
Notably, the giant `build_token` method had many aspects split off into separate methods. 
I also fixed some location tracking issues in the lexer.

### CODE REVIEW

**Comment by bjorn3** [comment]
Would it be feasible to do a 1-to-1 translation of librustc_lexer? The main file https://github.com/rust-lang/rust/blob/118860a7e76daaac3564c7655d46ac65a14fc612/src/librustc_lexer/src/lib.rs is 810 lines long. This would ensure full compatibility between rustc and gccrs on the lexer side and if there are any changes to the rustc lexer those would be very easy to port to gccrs. I don't know if that is acceptable from a license point of view though.

**Comment by SimplyTheOther** [comment]
A *complete* 1-1 translation? My understanding is no. librustc_lexer makes heavy use of tagged unions (“enum” in Rust - things like TokenKind in that file), which are not supported in C++11. There are workarounds for this, e.g. inheritance, but it would reduce performance (due to virtual function call) and also no longer be a 1-1 translation.

There’s also the issue of differences in how gccrs stores locations (rustc uses a “span”), and also the token format expected by each parser. Also, in my opinion, the lexer is probably the least complex part of the compiler (and the easiest to update), so I don’t think we’d get many advantages by using a 1-1 conversion of rustc’s.

There’s also the issue that rustc’s lexer system is a bit more complex than that. There is a second lexer [here](https://github.com/rust-lang/rust/blob/118860a7e76daaac3564c7655d46ac65a14fc612/src/librustc_parse/lexer/mod.rs), which apparently produces “rich tokens” or something. To get full functionality of their lexing, we’d need to copy that too.

**Comment by bjorn3** [comment]
> My understanding is no. librustc_lexer makes heavy use of tagged unions (“enum” in Rust - things like TokenKind in that file), which are not supported in C++11.

```c++
enum Base {
    Binary,
    Octal,
    Hexadecimal,
    Decimal,
};

struct LiteralKind {
    enum LiteralKindVariant {
        Int,
        Float,
    } kind;
    union LiteralKindData {
        struct Int { Base base; bool empty_int; } Int;
        struct Float { Base base; bool empty_exponent; } Float;
    } data;
};
```

works with `-std=c++11` with gcc 10.2.



> Also, in my opinion, the lexer is probably the least complex part of the compiler (and the easiest to update), so I don’t think we’d get many advantages by using a 1-1 conversion of rustc’s.

I see

**Comment by SimplyTheOther** [comment]
``` 
    union LiteralKindData {
        struct Int { Base base; bool empty_int; } Int;
        struct Float { Base base; bool empty_exponent; } Float;
    } data;
```

I was referring to type-safe tagged unions, i.e. something like ``std::variant`` in C++14. It would be very easy to accidentally use this kind of union incorrectly if you forgot to check the tag, or assumed that it should be a certain element, etc. ``union``s themselves actually have several other issues in addition to not being type-safe - they don't work with non-trivially constructible inner types unless you do hacks like placement new, you have to explicitly call destructors if you ever change the active element, and they're just a pain in general.

**Review by philberty — APPROVED** [review]

**Comment by philberty** [comment]
I agree with @SimplyTheOther I don't believe a 1-1 copy of the rust code is going to help us

**Pull request merged**
