### PR TITLE
Enhance AST dump

### PR DESCRIPTION
**Pull request by NalaGinrut**
See #7

### CODE REVIEW

**Comment by philberty** [comment]
the review in github is too large to review. It would be ideal for future PR's to split up the work into smaller commits if possible and expand on your commit message a little bit more. I am extremely guilty of this but its a habit i want to get out of.

Can you supply an example rust program your resting with as part of creating the review.

Off topic: I will review this properly locally tomorrow still working on a PR to do some static analysis work which i will ask both of you to review also.

**Comment by NalaGinrut** [comment]
@philberty I'm sorry but this PR is special since it mixed with the indentation fix. I understand they should be separated, but this work is before the topic of the indentation standard discussion. My idea is to merge it then fix the rest indentation with another PR, then we can start the better cooperation for code review. I think it's the cost for us in the very beginning cooperation. 

What do you think?
cc @SimplyTheOther

**Comment by philberty** [comment]
Ah ok yeah that makes sense if this includes some of the indentation fix do you want to add in the rest of the indentation fix into this PR and we can merge it so its done or do  you want to get this out of the way first?

**Comment by NalaGinrut** [comment]
@philberty The AST dump is not complete yet, but the mixed indentation issue may affect other contributors to make new things. So my idea is to merge it ASAP, and I'll raise a new PR for indentation ASAP. Then the world is back to normal. Alas... ;-)

**Comment by philberty** [comment]
cool beans i merged it now :)

**Pull request merged**
